/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // Array 中 key:value
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    
});

var cityArr = [
                '臺北市',
                '新北市',
                '台中市',
                '臺南市',
                '高雄市',
                '基隆市',
                '桃園區',
                '新竹市',
                '新竹縣',
                '苗栗縣',
                '彰化縣',
                '南投縣',
                '雲林縣',
                '嘉義市',
                '嘉義縣',
                '屏東縣',
                '宜蘭縣',
                '花蓮縣',
                '台東縣',
                '澎湖縣',
                '金門縣',
                '連江縣'
                ];       
    $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + cityArr[n] + '") and u="c"',
           format: 'json'
         },
         success: function (data) {
       var weatherInfo = data.query.results.channel;
       var date0 = weatherInfo.item.forecast[0].date;
           console.log(date0);
       var high0 = weatherInfo.item.forecast[0].high;
           console.log(high0);
       var low0 = weatherInfo.item.forecast[0].low;
           console.log(low0);
       var text0 = weatherInfo.item.forecast[0].text;
           console.log(text0);

       var date1 = weatherInfo.item.forecast[1].date;
           console.log(date1);
       var high1 = weatherInfo.item.forecast[1].high;
           console.log(high1);
       var low1 = weatherInfo.item.forecast[1].low;
           console.log(low1);
       var text1 = weatherInfo.item.forecast[1].text;
           console.log(text1);

       var date2 = weatherInfo.item.forecast[2].date;
           console.log(date2);
       var high2 = weatherInfo.item.forecast[2].high;
           console.log(high2);
       var low2 = weatherInfo.item.forecast[2].low;
           console.log(low2);
       var text2 = weatherInfo.item.forecast[2].text;
           console.log(text2);

       var date3 = weatherInfo.item.forecast[3].date;
           console.log(date3);
       var high3 = weatherInfo.item.forecast[3].high;
           console.log(high3);
       var low3 = weatherInfo.item.forecast[3].low;
           console.log(low3);
       var text3 = weatherInfo.item.forecast[3].text;
           console.log(text3);
         }
       });

       //回傳 onClick, find("name or num")
       $('#today.date').text();
       $('#today.condition').text();
       $('#today.temperature').text();

       $('#day1.date').text();
       $('#day1.condition').text();
       $('#day1.temperature').text();

       $('#day2.date').text();
       $('#day2.condition').text();
       $('#day2.temperature').text();

       $('#day3.date').text();
       $('#day3.condition').text();
       $('#day3.temperature').text();





